# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-web-frontend
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    app: crater-web-frontend
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/web-frontend/configmap.yaml") . | sha256sum }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crater-web-frontend
  template:
    metadata:
      labels:
        app: crater-web-frontend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: crater-web-frontend-container
          image: {{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: crater-web-frontend-config
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      tolerations: {{ .Values.tolerations | toYaml | nindent 8 }}