// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newModelDownloadSubmission(db *gorm.DB, opts ...gen.DOOption) modelDownloadSubmission {
	_modelDownloadSubmission := modelDownloadSubmission{}

	_modelDownloadSubmission.modelDownloadSubmissionDo.UseDB(db, opts...)
	_modelDownloadSubmission.modelDownloadSubmissionDo.UseModel(&model.ModelDownloadSubmission{})

	tableName := _modelDownloadSubmission.modelDownloadSubmissionDo.TableName()
	_modelDownloadSubmission.ALL = field.NewAsterisk(tableName)
	_modelDownloadSubmission.ID = field.NewUint(tableName, "id")
	_modelDownloadSubmission.UserID = field.NewUint(tableName, "user_id")
	_modelDownloadSubmission.ModelDownloadID = field.NewUint(tableName, "model_download_id")
	_modelDownloadSubmission.Action = field.NewString(tableName, "action")
	_modelDownloadSubmission.Status = field.NewString(tableName, "status")
	_modelDownloadSubmission.CreatedAt = field.NewTime(tableName, "created_at")
	_modelDownloadSubmission.CompletedAt = field.NewTime(tableName, "completed_at")

	_modelDownloadSubmission.fillFieldMap()

	return _modelDownloadSubmission
}

type modelDownloadSubmission struct {
	modelDownloadSubmissionDo modelDownloadSubmissionDo

	ALL             field.Asterisk
	ID              field.Uint
	UserID          field.Uint
	ModelDownloadID field.Uint
	Action          field.String
	Status          field.String
	CreatedAt       field.Time
	CompletedAt     field.Time

	fieldMap map[string]field.Expr
}

func (m modelDownloadSubmission) Table(newTableName string) *modelDownloadSubmission {
	m.modelDownloadSubmissionDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modelDownloadSubmission) As(alias string) *modelDownloadSubmission {
	m.modelDownloadSubmissionDo.DO = *(m.modelDownloadSubmissionDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modelDownloadSubmission) updateTableName(table string) *modelDownloadSubmission {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.UserID = field.NewUint(table, "user_id")
	m.ModelDownloadID = field.NewUint(table, "model_download_id")
	m.Action = field.NewString(table, "action")
	m.Status = field.NewString(table, "status")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.CompletedAt = field.NewTime(table, "completed_at")

	m.fillFieldMap()

	return m
}

func (m *modelDownloadSubmission) WithContext(ctx context.Context) IModelDownloadSubmissionDo {
	return m.modelDownloadSubmissionDo.WithContext(ctx)
}

func (m modelDownloadSubmission) TableName() string { return m.modelDownloadSubmissionDo.TableName() }

func (m modelDownloadSubmission) Alias() string { return m.modelDownloadSubmissionDo.Alias() }

func (m modelDownloadSubmission) Columns(cols ...field.Expr) gen.Columns {
	return m.modelDownloadSubmissionDo.Columns(cols...)
}

func (m *modelDownloadSubmission) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modelDownloadSubmission) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 7)
	m.fieldMap["id"] = m.ID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["model_download_id"] = m.ModelDownloadID
	m.fieldMap["action"] = m.Action
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["completed_at"] = m.CompletedAt
}

func (m modelDownloadSubmission) clone(db *gorm.DB) modelDownloadSubmission {
	m.modelDownloadSubmissionDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m modelDownloadSubmission) replaceDB(db *gorm.DB) modelDownloadSubmission {
	m.modelDownloadSubmissionDo.ReplaceDB(db)
	return m
}

type modelDownloadSubmissionDo struct{ gen.DO }

type IModelDownloadSubmissionDo interface {
	gen.SubQuery
	Debug() IModelDownloadSubmissionDo
	WithContext(ctx context.Context) IModelDownloadSubmissionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModelDownloadSubmissionDo
	WriteDB() IModelDownloadSubmissionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModelDownloadSubmissionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModelDownloadSubmissionDo
	Not(conds ...gen.Condition) IModelDownloadSubmissionDo
	Or(conds ...gen.Condition) IModelDownloadSubmissionDo
	Select(conds ...field.Expr) IModelDownloadSubmissionDo
	Where(conds ...gen.Condition) IModelDownloadSubmissionDo
	Order(conds ...field.Expr) IModelDownloadSubmissionDo
	Distinct(cols ...field.Expr) IModelDownloadSubmissionDo
	Omit(cols ...field.Expr) IModelDownloadSubmissionDo
	Join(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo
	Group(cols ...field.Expr) IModelDownloadSubmissionDo
	Having(conds ...gen.Condition) IModelDownloadSubmissionDo
	Limit(limit int) IModelDownloadSubmissionDo
	Offset(offset int) IModelDownloadSubmissionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDownloadSubmissionDo
	Unscoped() IModelDownloadSubmissionDo
	Create(values ...*model.ModelDownloadSubmission) error
	CreateInBatches(values []*model.ModelDownloadSubmission, batchSize int) error
	Save(values ...*model.ModelDownloadSubmission) error
	First() (*model.ModelDownloadSubmission, error)
	Take() (*model.ModelDownloadSubmission, error)
	Last() (*model.ModelDownloadSubmission, error)
	Find() ([]*model.ModelDownloadSubmission, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModelDownloadSubmission, err error)
	FindInBatches(result *[]*model.ModelDownloadSubmission, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ModelDownloadSubmission) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModelDownloadSubmissionDo
	Assign(attrs ...field.AssignExpr) IModelDownloadSubmissionDo
	Joins(fields ...field.RelationField) IModelDownloadSubmissionDo
	Preload(fields ...field.RelationField) IModelDownloadSubmissionDo
	FirstOrInit() (*model.ModelDownloadSubmission, error)
	FirstOrCreate() (*model.ModelDownloadSubmission, error)
	FindByPage(offset int, limit int) (result []*model.ModelDownloadSubmission, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModelDownloadSubmissionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modelDownloadSubmissionDo) Debug() IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Debug())
}

func (m modelDownloadSubmissionDo) WithContext(ctx context.Context) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelDownloadSubmissionDo) ReadDB() IModelDownloadSubmissionDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelDownloadSubmissionDo) WriteDB() IModelDownloadSubmissionDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelDownloadSubmissionDo) Session(config *gorm.Session) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelDownloadSubmissionDo) Clauses(conds ...clause.Expression) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelDownloadSubmissionDo) Returning(value interface{}, columns ...string) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelDownloadSubmissionDo) Not(conds ...gen.Condition) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelDownloadSubmissionDo) Or(conds ...gen.Condition) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelDownloadSubmissionDo) Select(conds ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelDownloadSubmissionDo) Where(conds ...gen.Condition) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelDownloadSubmissionDo) Order(conds ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelDownloadSubmissionDo) Distinct(cols ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelDownloadSubmissionDo) Omit(cols ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelDownloadSubmissionDo) Join(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelDownloadSubmissionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelDownloadSubmissionDo) RightJoin(table schema.Tabler, on ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelDownloadSubmissionDo) Group(cols ...field.Expr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelDownloadSubmissionDo) Having(conds ...gen.Condition) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelDownloadSubmissionDo) Limit(limit int) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelDownloadSubmissionDo) Offset(offset int) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelDownloadSubmissionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelDownloadSubmissionDo) Unscoped() IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelDownloadSubmissionDo) Create(values ...*model.ModelDownloadSubmission) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelDownloadSubmissionDo) CreateInBatches(values []*model.ModelDownloadSubmission, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelDownloadSubmissionDo) Save(values ...*model.ModelDownloadSubmission) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelDownloadSubmissionDo) First() (*model.ModelDownloadSubmission, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownloadSubmission), nil
	}
}

func (m modelDownloadSubmissionDo) Take() (*model.ModelDownloadSubmission, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownloadSubmission), nil
	}
}

func (m modelDownloadSubmissionDo) Last() (*model.ModelDownloadSubmission, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownloadSubmission), nil
	}
}

func (m modelDownloadSubmissionDo) Find() ([]*model.ModelDownloadSubmission, error) {
	result, err := m.DO.Find()
	return result.([]*model.ModelDownloadSubmission), err
}

func (m modelDownloadSubmissionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModelDownloadSubmission, err error) {
	buf := make([]*model.ModelDownloadSubmission, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelDownloadSubmissionDo) FindInBatches(result *[]*model.ModelDownloadSubmission, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelDownloadSubmissionDo) Attrs(attrs ...field.AssignExpr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelDownloadSubmissionDo) Assign(attrs ...field.AssignExpr) IModelDownloadSubmissionDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelDownloadSubmissionDo) Joins(fields ...field.RelationField) IModelDownloadSubmissionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelDownloadSubmissionDo) Preload(fields ...field.RelationField) IModelDownloadSubmissionDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelDownloadSubmissionDo) FirstOrInit() (*model.ModelDownloadSubmission, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownloadSubmission), nil
	}
}

func (m modelDownloadSubmissionDo) FirstOrCreate() (*model.ModelDownloadSubmission, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownloadSubmission), nil
	}
}

func (m modelDownloadSubmissionDo) FindByPage(offset int, limit int) (result []*model.ModelDownloadSubmission, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelDownloadSubmissionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelDownloadSubmissionDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelDownloadSubmissionDo) Delete(models ...*model.ModelDownloadSubmission) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelDownloadSubmissionDo) withDO(do gen.Dao) *modelDownloadSubmissionDo {
	m.DO = *do.(*gen.DO)
	return m
}
