// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newModelDownload(db *gorm.DB, opts ...gen.DOOption) modelDownload {
	_modelDownload := modelDownload{}

	_modelDownload.modelDownloadDo.UseDB(db, opts...)
	_modelDownload.modelDownloadDo.UseModel(&model.ModelDownload{})

	tableName := _modelDownload.modelDownloadDo.TableName()
	_modelDownload.ALL = field.NewAsterisk(tableName)
	_modelDownload.ID = field.NewUint(tableName, "id")
	_modelDownload.CreatedAt = field.NewTime(tableName, "created_at")
	_modelDownload.UpdatedAt = field.NewTime(tableName, "updated_at")
	_modelDownload.DeletedAt = field.NewField(tableName, "deleted_at")
	_modelDownload.Name = field.NewString(tableName, "name")
	_modelDownload.Source = field.NewString(tableName, "source")
	_modelDownload.Category = field.NewString(tableName, "category")
	_modelDownload.Revision = field.NewString(tableName, "revision")
	_modelDownload.Path = field.NewString(tableName, "path")
	_modelDownload.SizeBytes = field.NewInt64(tableName, "size_bytes")
	_modelDownload.DownloadedBytes = field.NewInt64(tableName, "downloaded_bytes")
	_modelDownload.DownloadSpeed = field.NewString(tableName, "download_speed")
	_modelDownload.Status = field.NewString(tableName, "status")
	_modelDownload.Message = field.NewString(tableName, "message")
	_modelDownload.Logs = field.NewString(tableName, "logs")
	_modelDownload.LogsSavedAt = field.NewTime(tableName, "logs_saved_at")
	_modelDownload.Organization = field.NewString(tableName, "organization")
	_modelDownload.LogoURL = field.NewString(tableName, "logo_url")
	_modelDownload.SourceURL = field.NewString(tableName, "source_url")
	_modelDownload.DisplayName = field.NewString(tableName, "display_name")
	_modelDownload.SourceDescription = field.NewString(tableName, "source_description")
	_modelDownload.SourceReadme = field.NewString(tableName, "source_readme")
	_modelDownload.License = field.NewString(tableName, "license")
	_modelDownload.Task = field.NewString(tableName, "task")
	_modelDownload.Library = field.NewString(tableName, "library")
	_modelDownload.ModelType = field.NewString(tableName, "model_type")
	_modelDownload.ParameterCount = field.NewInt64(tableName, "parameter_count")
	_modelDownload.SourcePrivate = field.NewBool(tableName, "source_private")
	_modelDownload.SourceGated = field.NewBool(tableName, "source_gated")
	_modelDownload.SourceLoginRequired = field.NewBool(tableName, "source_login_required")
	_modelDownload.SourceDownloads = field.NewInt64(tableName, "source_downloads")
	_modelDownload.SourceLikes = field.NewInt64(tableName, "source_likes")
	_modelDownload.SourceCreatedAt = field.NewTime(tableName, "source_created_at")
	_modelDownload.SourceUpdatedAt = field.NewTime(tableName, "source_updated_at")
	_modelDownload.MetadataRefreshedAt = field.NewTime(tableName, "metadata_refreshed_at")
	_modelDownload.JobName = field.NewString(tableName, "job_name")
	_modelDownload.CreatorID = field.NewUint(tableName, "creator_id")
	_modelDownload.ReferenceCount = field.NewInt(tableName, "reference_count")
	_modelDownload.Creator = modelDownloadBelongsToCreator{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Creator", "model.User"),
		UserAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Creator.UserAccounts", "model.UserAccount"),
		},
		UserDatasets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("Creator.UserDatasets", "model.UserDataset"),
		},
	}

	_modelDownload.fillFieldMap()

	return _modelDownload
}

type modelDownload struct {
	modelDownloadDo modelDownloadDo

	ALL                 field.Asterisk
	ID                  field.Uint
	CreatedAt           field.Time
	UpdatedAt           field.Time
	DeletedAt           field.Field
	Name                field.String
	Source              field.String
	Category            field.String
	Revision            field.String // 版本/分支/commit
	Path                field.String // 实际下载路径
	SizeBytes           field.Int64  // 文件总大小(字节)
	DownloadedBytes     field.Int64  // 已下载大小(字节)
	DownloadSpeed       field.String // 下载速度(如: 10MB/s)
	Status              field.String // 下载状态
	Message             field.String // 状态消息(错误信息等)
	Logs                field.String // 终态时保存的Pod日志(K8s Job被GC后仍可查看)
	LogsSavedAt         field.Time   // 日志保存时间
	Organization        field.String // 源站组织或作者
	LogoURL             field.String // 源站组织头像地址
	SourceURL           field.String // 源站仓库详情地址
	DisplayName         field.String // 源站展示名称
	SourceDescription   field.String // 源站简介摘要
	SourceReadme        field.String // 源站README内容(截断保存)
	License             field.String // 源站许可证
	Task                field.String // 源站任务分类
	Library             field.String // 源站框架或库
	ModelType           field.String // 源站模型类型
	ParameterCount      field.Int64  // 模型参数量
	SourcePrivate       field.Bool   // 源站是否私有
	SourceGated         field.Bool   // 源站是否需要申请访问
	SourceLoginRequired field.Bool   // 源站是否要求登录下载
	SourceDownloads     field.Int64  // 源站下载次数
	SourceLikes         field.Int64  // 源站点赞次数
	SourceCreatedAt     field.Time   // 源站创建时间
	SourceUpdatedAt     field.Time   // 源站更新时间
	MetadataRefreshedAt field.Time   // 源站元数据刷新时间
	JobName             field.String // K8s Job名称
	CreatorID           field.Uint   // 首个发起下载的用户ID
	ReferenceCount      field.Int    // 引用计数
	Creator             modelDownloadBelongsToCreator

	fieldMap map[string]field.Expr
}

func (m modelDownload) Table(newTableName string) *modelDownload {
	m.modelDownloadDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m modelDownload) As(alias string) *modelDownload {
	m.modelDownloadDo.DO = *(m.modelDownloadDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *modelDownload) updateTableName(table string) *modelDownload {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewUint(table, "id")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")
	m.Name = field.NewString(table, "name")
	m.Source = field.NewString(table, "source")
	m.Category = field.NewString(table, "category")
	m.Revision = field.NewString(table, "revision")
	m.Path = field.NewString(table, "path")
	m.SizeBytes = field.NewInt64(table, "size_bytes")
	m.DownloadedBytes = field.NewInt64(table, "downloaded_bytes")
	m.DownloadSpeed = field.NewString(table, "download_speed")
	m.Status = field.NewString(table, "status")
	m.Message = field.NewString(table, "message")
	m.Logs = field.NewString(table, "logs")
	m.LogsSavedAt = field.NewTime(table, "logs_saved_at")
	m.Organization = field.NewString(table, "organization")
	m.LogoURL = field.NewString(table, "logo_url")
	m.SourceURL = field.NewString(table, "source_url")
	m.DisplayName = field.NewString(table, "display_name")
	m.SourceDescription = field.NewString(table, "source_description")
	m.SourceReadme = field.NewString(table, "source_readme")
	m.License = field.NewString(table, "license")
	m.Task = field.NewString(table, "task")
	m.Library = field.NewString(table, "library")
	m.ModelType = field.NewString(table, "model_type")
	m.ParameterCount = field.NewInt64(table, "parameter_count")
	m.SourcePrivate = field.NewBool(table, "source_private")
	m.SourceGated = field.NewBool(table, "source_gated")
	m.SourceLoginRequired = field.NewBool(table, "source_login_required")
	m.SourceDownloads = field.NewInt64(table, "source_downloads")
	m.SourceLikes = field.NewInt64(table, "source_likes")
	m.SourceCreatedAt = field.NewTime(table, "source_created_at")
	m.SourceUpdatedAt = field.NewTime(table, "source_updated_at")
	m.MetadataRefreshedAt = field.NewTime(table, "metadata_refreshed_at")
	m.JobName = field.NewString(table, "job_name")
	m.CreatorID = field.NewUint(table, "creator_id")
	m.ReferenceCount = field.NewInt(table, "reference_count")

	m.fillFieldMap()

	return m
}

func (m *modelDownload) WithContext(ctx context.Context) IModelDownloadDo {
	return m.modelDownloadDo.WithContext(ctx)
}

func (m modelDownload) TableName() string { return m.modelDownloadDo.TableName() }

func (m modelDownload) Alias() string { return m.modelDownloadDo.Alias() }

func (m modelDownload) Columns(cols ...field.Expr) gen.Columns {
	return m.modelDownloadDo.Columns(cols...)
}

func (m *modelDownload) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *modelDownload) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 39)
	m.fieldMap["id"] = m.ID
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt
	m.fieldMap["name"] = m.Name
	m.fieldMap["source"] = m.Source
	m.fieldMap["category"] = m.Category
	m.fieldMap["revision"] = m.Revision
	m.fieldMap["path"] = m.Path
	m.fieldMap["size_bytes"] = m.SizeBytes
	m.fieldMap["downloaded_bytes"] = m.DownloadedBytes
	m.fieldMap["download_speed"] = m.DownloadSpeed
	m.fieldMap["status"] = m.Status
	m.fieldMap["message"] = m.Message
	m.fieldMap["logs"] = m.Logs
	m.fieldMap["logs_saved_at"] = m.LogsSavedAt
	m.fieldMap["organization"] = m.Organization
	m.fieldMap["logo_url"] = m.LogoURL
	m.fieldMap["source_url"] = m.SourceURL
	m.fieldMap["display_name"] = m.DisplayName
	m.fieldMap["source_description"] = m.SourceDescription
	m.fieldMap["source_readme"] = m.SourceReadme
	m.fieldMap["license"] = m.License
	m.fieldMap["task"] = m.Task
	m.fieldMap["library"] = m.Library
	m.fieldMap["model_type"] = m.ModelType
	m.fieldMap["parameter_count"] = m.ParameterCount
	m.fieldMap["source_private"] = m.SourcePrivate
	m.fieldMap["source_gated"] = m.SourceGated
	m.fieldMap["source_login_required"] = m.SourceLoginRequired
	m.fieldMap["source_downloads"] = m.SourceDownloads
	m.fieldMap["source_likes"] = m.SourceLikes
	m.fieldMap["source_created_at"] = m.SourceCreatedAt
	m.fieldMap["source_updated_at"] = m.SourceUpdatedAt
	m.fieldMap["metadata_refreshed_at"] = m.MetadataRefreshedAt
	m.fieldMap["job_name"] = m.JobName
	m.fieldMap["creator_id"] = m.CreatorID
	m.fieldMap["reference_count"] = m.ReferenceCount

}

func (m modelDownload) clone(db *gorm.DB) modelDownload {
	m.modelDownloadDo.ReplaceConnPool(db.Statement.ConnPool)
	m.Creator.db = db.Session(&gorm.Session{Initialized: true})
	m.Creator.db.Statement.ConnPool = db.Statement.ConnPool
	return m
}

func (m modelDownload) replaceDB(db *gorm.DB) modelDownload {
	m.modelDownloadDo.ReplaceDB(db)
	m.Creator.db = db.Session(&gorm.Session{})
	return m
}

type modelDownloadBelongsToCreator struct {
	db *gorm.DB

	field.RelationField

	UserAccounts struct {
		field.RelationField
	}
	UserDatasets struct {
		field.RelationField
	}
}

func (a modelDownloadBelongsToCreator) Where(conds ...field.Expr) *modelDownloadBelongsToCreator {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a modelDownloadBelongsToCreator) WithContext(ctx context.Context) *modelDownloadBelongsToCreator {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a modelDownloadBelongsToCreator) Session(session *gorm.Session) *modelDownloadBelongsToCreator {
	a.db = a.db.Session(session)
	return &a
}

func (a modelDownloadBelongsToCreator) Model(m *model.ModelDownload) *modelDownloadBelongsToCreatorTx {
	return &modelDownloadBelongsToCreatorTx{a.db.Model(m).Association(a.Name())}
}

func (a modelDownloadBelongsToCreator) Unscoped() *modelDownloadBelongsToCreator {
	a.db = a.db.Unscoped()
	return &a
}

type modelDownloadBelongsToCreatorTx struct{ tx *gorm.Association }

func (a modelDownloadBelongsToCreatorTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a modelDownloadBelongsToCreatorTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a modelDownloadBelongsToCreatorTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a modelDownloadBelongsToCreatorTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a modelDownloadBelongsToCreatorTx) Clear() error {
	return a.tx.Clear()
}

func (a modelDownloadBelongsToCreatorTx) Count() int64 {
	return a.tx.Count()
}

func (a modelDownloadBelongsToCreatorTx) Unscoped() *modelDownloadBelongsToCreatorTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type modelDownloadDo struct{ gen.DO }

type IModelDownloadDo interface {
	gen.SubQuery
	Debug() IModelDownloadDo
	WithContext(ctx context.Context) IModelDownloadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IModelDownloadDo
	WriteDB() IModelDownloadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IModelDownloadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IModelDownloadDo
	Not(conds ...gen.Condition) IModelDownloadDo
	Or(conds ...gen.Condition) IModelDownloadDo
	Select(conds ...field.Expr) IModelDownloadDo
	Where(conds ...gen.Condition) IModelDownloadDo
	Order(conds ...field.Expr) IModelDownloadDo
	Distinct(cols ...field.Expr) IModelDownloadDo
	Omit(cols ...field.Expr) IModelDownloadDo
	Join(table schema.Tabler, on ...field.Expr) IModelDownloadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IModelDownloadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IModelDownloadDo
	Group(cols ...field.Expr) IModelDownloadDo
	Having(conds ...gen.Condition) IModelDownloadDo
	Limit(limit int) IModelDownloadDo
	Offset(offset int) IModelDownloadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDownloadDo
	Unscoped() IModelDownloadDo
	Create(values ...*model.ModelDownload) error
	CreateInBatches(values []*model.ModelDownload, batchSize int) error
	Save(values ...*model.ModelDownload) error
	First() (*model.ModelDownload, error)
	Take() (*model.ModelDownload, error)
	Last() (*model.ModelDownload, error)
	Find() ([]*model.ModelDownload, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModelDownload, err error)
	FindInBatches(result *[]*model.ModelDownload, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ModelDownload) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IModelDownloadDo
	Assign(attrs ...field.AssignExpr) IModelDownloadDo
	Joins(fields ...field.RelationField) IModelDownloadDo
	Preload(fields ...field.RelationField) IModelDownloadDo
	FirstOrInit() (*model.ModelDownload, error)
	FirstOrCreate() (*model.ModelDownload, error)
	FindByPage(offset int, limit int) (result []*model.ModelDownload, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IModelDownloadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m modelDownloadDo) Debug() IModelDownloadDo {
	return m.withDO(m.DO.Debug())
}

func (m modelDownloadDo) WithContext(ctx context.Context) IModelDownloadDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m modelDownloadDo) ReadDB() IModelDownloadDo {
	return m.Clauses(dbresolver.Read)
}

func (m modelDownloadDo) WriteDB() IModelDownloadDo {
	return m.Clauses(dbresolver.Write)
}

func (m modelDownloadDo) Session(config *gorm.Session) IModelDownloadDo {
	return m.withDO(m.DO.Session(config))
}

func (m modelDownloadDo) Clauses(conds ...clause.Expression) IModelDownloadDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m modelDownloadDo) Returning(value interface{}, columns ...string) IModelDownloadDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m modelDownloadDo) Not(conds ...gen.Condition) IModelDownloadDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m modelDownloadDo) Or(conds ...gen.Condition) IModelDownloadDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m modelDownloadDo) Select(conds ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m modelDownloadDo) Where(conds ...gen.Condition) IModelDownloadDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m modelDownloadDo) Order(conds ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m modelDownloadDo) Distinct(cols ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m modelDownloadDo) Omit(cols ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m modelDownloadDo) Join(table schema.Tabler, on ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m modelDownloadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m modelDownloadDo) RightJoin(table schema.Tabler, on ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m modelDownloadDo) Group(cols ...field.Expr) IModelDownloadDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m modelDownloadDo) Having(conds ...gen.Condition) IModelDownloadDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m modelDownloadDo) Limit(limit int) IModelDownloadDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m modelDownloadDo) Offset(offset int) IModelDownloadDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m modelDownloadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IModelDownloadDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m modelDownloadDo) Unscoped() IModelDownloadDo {
	return m.withDO(m.DO.Unscoped())
}

func (m modelDownloadDo) Create(values ...*model.ModelDownload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m modelDownloadDo) CreateInBatches(values []*model.ModelDownload, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m modelDownloadDo) Save(values ...*model.ModelDownload) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m modelDownloadDo) First() (*model.ModelDownload, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownload), nil
	}
}

func (m modelDownloadDo) Take() (*model.ModelDownload, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownload), nil
	}
}

func (m modelDownloadDo) Last() (*model.ModelDownload, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownload), nil
	}
}

func (m modelDownloadDo) Find() ([]*model.ModelDownload, error) {
	result, err := m.DO.Find()
	return result.([]*model.ModelDownload), err
}

func (m modelDownloadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ModelDownload, err error) {
	buf := make([]*model.ModelDownload, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m modelDownloadDo) FindInBatches(result *[]*model.ModelDownload, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m modelDownloadDo) Attrs(attrs ...field.AssignExpr) IModelDownloadDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m modelDownloadDo) Assign(attrs ...field.AssignExpr) IModelDownloadDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m modelDownloadDo) Joins(fields ...field.RelationField) IModelDownloadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m modelDownloadDo) Preload(fields ...field.RelationField) IModelDownloadDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m modelDownloadDo) FirstOrInit() (*model.ModelDownload, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownload), nil
	}
}

func (m modelDownloadDo) FirstOrCreate() (*model.ModelDownload, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ModelDownload), nil
	}
}

func (m modelDownloadDo) FindByPage(offset int, limit int) (result []*model.ModelDownload, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m modelDownloadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m modelDownloadDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m modelDownloadDo) Delete(models ...*model.ModelDownload) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *modelDownloadDo) withDO(do gen.Dao) *modelDownloadDo {
	m.DO = *do.(*gen.DO)
	return m
}
