// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newPrequeueConfig(db *gorm.DB, opts ...gen.DOOption) prequeueConfig {
	_prequeueConfig := prequeueConfig{}

	_prequeueConfig.prequeueConfigDo.UseDB(db, opts...)
	_prequeueConfig.prequeueConfigDo.UseModel(&model.PrequeueConfig{})

	tableName := _prequeueConfig.prequeueConfigDo.TableName()
	_prequeueConfig.ALL = field.NewAsterisk(tableName)
	_prequeueConfig.ID = field.NewUint(tableName, "id")
	_prequeueConfig.CreatedAt = field.NewTime(tableName, "created_at")
	_prequeueConfig.UpdatedAt = field.NewTime(tableName, "updated_at")
	_prequeueConfig.DeletedAt = field.NewField(tableName, "deleted_at")
	_prequeueConfig.Key = field.NewString(tableName, "key")
	_prequeueConfig.Value = field.NewString(tableName, "value")
	_prequeueConfig.ExpireAt = field.NewTime(tableName, "expire_at")

	_prequeueConfig.fillFieldMap()

	return _prequeueConfig
}

type prequeueConfig struct {
	prequeueConfigDo prequeueConfigDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Key       field.String // 配置项的键
	Value     field.String // 配置项的值
	ExpireAt  field.Time   // 配置项过期时间

	fieldMap map[string]field.Expr
}

func (p prequeueConfig) Table(newTableName string) *prequeueConfig {
	p.prequeueConfigDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p prequeueConfig) As(alias string) *prequeueConfig {
	p.prequeueConfigDo.DO = *(p.prequeueConfigDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *prequeueConfig) updateTableName(table string) *prequeueConfig {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewUint(table, "id")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewField(table, "deleted_at")
	p.Key = field.NewString(table, "key")
	p.Value = field.NewString(table, "value")
	p.ExpireAt = field.NewTime(table, "expire_at")

	p.fillFieldMap()

	return p
}

func (p *prequeueConfig) WithContext(ctx context.Context) IPrequeueConfigDo {
	return p.prequeueConfigDo.WithContext(ctx)
}

func (p prequeueConfig) TableName() string { return p.prequeueConfigDo.TableName() }

func (p prequeueConfig) Alias() string { return p.prequeueConfigDo.Alias() }

func (p prequeueConfig) Columns(cols ...field.Expr) gen.Columns {
	return p.prequeueConfigDo.Columns(cols...)
}

func (p *prequeueConfig) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *prequeueConfig) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 7)
	p.fieldMap["id"] = p.ID
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
	p.fieldMap["key"] = p.Key
	p.fieldMap["value"] = p.Value
	p.fieldMap["expire_at"] = p.ExpireAt
}

func (p prequeueConfig) clone(db *gorm.DB) prequeueConfig {
	p.prequeueConfigDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p prequeueConfig) replaceDB(db *gorm.DB) prequeueConfig {
	p.prequeueConfigDo.ReplaceDB(db)
	return p
}

type prequeueConfigDo struct{ gen.DO }

type IPrequeueConfigDo interface {
	gen.SubQuery
	Debug() IPrequeueConfigDo
	WithContext(ctx context.Context) IPrequeueConfigDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPrequeueConfigDo
	WriteDB() IPrequeueConfigDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPrequeueConfigDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPrequeueConfigDo
	Not(conds ...gen.Condition) IPrequeueConfigDo
	Or(conds ...gen.Condition) IPrequeueConfigDo
	Select(conds ...field.Expr) IPrequeueConfigDo
	Where(conds ...gen.Condition) IPrequeueConfigDo
	Order(conds ...field.Expr) IPrequeueConfigDo
	Distinct(cols ...field.Expr) IPrequeueConfigDo
	Omit(cols ...field.Expr) IPrequeueConfigDo
	Join(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo
	Group(cols ...field.Expr) IPrequeueConfigDo
	Having(conds ...gen.Condition) IPrequeueConfigDo
	Limit(limit int) IPrequeueConfigDo
	Offset(offset int) IPrequeueConfigDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPrequeueConfigDo
	Unscoped() IPrequeueConfigDo
	Create(values ...*model.PrequeueConfig) error
	CreateInBatches(values []*model.PrequeueConfig, batchSize int) error
	Save(values ...*model.PrequeueConfig) error
	First() (*model.PrequeueConfig, error)
	Take() (*model.PrequeueConfig, error)
	Last() (*model.PrequeueConfig, error)
	Find() ([]*model.PrequeueConfig, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrequeueConfig, err error)
	FindInBatches(result *[]*model.PrequeueConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PrequeueConfig) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPrequeueConfigDo
	Assign(attrs ...field.AssignExpr) IPrequeueConfigDo
	Joins(fields ...field.RelationField) IPrequeueConfigDo
	Preload(fields ...field.RelationField) IPrequeueConfigDo
	FirstOrInit() (*model.PrequeueConfig, error)
	FirstOrCreate() (*model.PrequeueConfig, error)
	FindByPage(offset int, limit int) (result []*model.PrequeueConfig, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPrequeueConfigDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p prequeueConfigDo) Debug() IPrequeueConfigDo {
	return p.withDO(p.DO.Debug())
}

func (p prequeueConfigDo) WithContext(ctx context.Context) IPrequeueConfigDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p prequeueConfigDo) ReadDB() IPrequeueConfigDo {
	return p.Clauses(dbresolver.Read)
}

func (p prequeueConfigDo) WriteDB() IPrequeueConfigDo {
	return p.Clauses(dbresolver.Write)
}

func (p prequeueConfigDo) Session(config *gorm.Session) IPrequeueConfigDo {
	return p.withDO(p.DO.Session(config))
}

func (p prequeueConfigDo) Clauses(conds ...clause.Expression) IPrequeueConfigDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p prequeueConfigDo) Returning(value interface{}, columns ...string) IPrequeueConfigDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p prequeueConfigDo) Not(conds ...gen.Condition) IPrequeueConfigDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p prequeueConfigDo) Or(conds ...gen.Condition) IPrequeueConfigDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p prequeueConfigDo) Select(conds ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p prequeueConfigDo) Where(conds ...gen.Condition) IPrequeueConfigDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p prequeueConfigDo) Order(conds ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p prequeueConfigDo) Distinct(cols ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p prequeueConfigDo) Omit(cols ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p prequeueConfigDo) Join(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p prequeueConfigDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p prequeueConfigDo) RightJoin(table schema.Tabler, on ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p prequeueConfigDo) Group(cols ...field.Expr) IPrequeueConfigDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p prequeueConfigDo) Having(conds ...gen.Condition) IPrequeueConfigDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p prequeueConfigDo) Limit(limit int) IPrequeueConfigDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p prequeueConfigDo) Offset(offset int) IPrequeueConfigDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p prequeueConfigDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPrequeueConfigDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p prequeueConfigDo) Unscoped() IPrequeueConfigDo {
	return p.withDO(p.DO.Unscoped())
}

func (p prequeueConfigDo) Create(values ...*model.PrequeueConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p prequeueConfigDo) CreateInBatches(values []*model.PrequeueConfig, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p prequeueConfigDo) Save(values ...*model.PrequeueConfig) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p prequeueConfigDo) First() (*model.PrequeueConfig, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrequeueConfig), nil
	}
}

func (p prequeueConfigDo) Take() (*model.PrequeueConfig, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrequeueConfig), nil
	}
}

func (p prequeueConfigDo) Last() (*model.PrequeueConfig, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrequeueConfig), nil
	}
}

func (p prequeueConfigDo) Find() ([]*model.PrequeueConfig, error) {
	result, err := p.DO.Find()
	return result.([]*model.PrequeueConfig), err
}

func (p prequeueConfigDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PrequeueConfig, err error) {
	buf := make([]*model.PrequeueConfig, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p prequeueConfigDo) FindInBatches(result *[]*model.PrequeueConfig, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p prequeueConfigDo) Attrs(attrs ...field.AssignExpr) IPrequeueConfigDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p prequeueConfigDo) Assign(attrs ...field.AssignExpr) IPrequeueConfigDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p prequeueConfigDo) Joins(fields ...field.RelationField) IPrequeueConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p prequeueConfigDo) Preload(fields ...field.RelationField) IPrequeueConfigDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p prequeueConfigDo) FirstOrInit() (*model.PrequeueConfig, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrequeueConfig), nil
	}
}

func (p prequeueConfigDo) FirstOrCreate() (*model.PrequeueConfig, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PrequeueConfig), nil
	}
}

func (p prequeueConfigDo) FindByPage(offset int, limit int) (result []*model.PrequeueConfig, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p prequeueConfigDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p prequeueConfigDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p prequeueConfigDo) Delete(models ...*model.PrequeueConfig) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *prequeueConfigDo) withDO(do gen.Dao) *prequeueConfigDo {
	p.DO = *do.(*gen.DO)
	return p
}
