// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newQueueQuotaLimit(db *gorm.DB, opts ...gen.DOOption) queueQuotaLimit {
	_queueQuotaLimit := queueQuotaLimit{}

	_queueQuotaLimit.queueQuotaLimitDo.UseDB(db, opts...)
	_queueQuotaLimit.queueQuotaLimitDo.UseModel(&model.QueueQuotaLimit{})

	tableName := _queueQuotaLimit.queueQuotaLimitDo.TableName()
	_queueQuotaLimit.ALL = field.NewAsterisk(tableName)
	_queueQuotaLimit.ID = field.NewUint(tableName, "id")
	_queueQuotaLimit.CreatedAt = field.NewTime(tableName, "created_at")
	_queueQuotaLimit.UpdatedAt = field.NewTime(tableName, "updated_at")
	_queueQuotaLimit.DeletedAt = field.NewField(tableName, "deleted_at")
	_queueQuotaLimit.Name = field.NewString(tableName, "name")
	_queueQuotaLimit.Quota = field.NewField(tableName, "quota")

	_queueQuotaLimit.fillFieldMap()

	return _queueQuotaLimit
}

type queueQuotaLimit struct {
	queueQuotaLimitDo queueQuotaLimitDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	Name      field.String // 队列名字
	Quota     field.Field  // 队列内资源限制

	fieldMap map[string]field.Expr
}

func (q queueQuotaLimit) Table(newTableName string) *queueQuotaLimit {
	q.queueQuotaLimitDo.UseTable(newTableName)
	return q.updateTableName(newTableName)
}

func (q queueQuotaLimit) As(alias string) *queueQuotaLimit {
	q.queueQuotaLimitDo.DO = *(q.queueQuotaLimitDo.As(alias).(*gen.DO))
	return q.updateTableName(alias)
}

func (q *queueQuotaLimit) updateTableName(table string) *queueQuotaLimit {
	q.ALL = field.NewAsterisk(table)
	q.ID = field.NewUint(table, "id")
	q.CreatedAt = field.NewTime(table, "created_at")
	q.UpdatedAt = field.NewTime(table, "updated_at")
	q.DeletedAt = field.NewField(table, "deleted_at")
	q.Name = field.NewString(table, "name")
	q.Quota = field.NewField(table, "quota")

	q.fillFieldMap()

	return q
}

func (q *queueQuotaLimit) WithContext(ctx context.Context) IQueueQuotaLimitDo {
	return q.queueQuotaLimitDo.WithContext(ctx)
}

func (q queueQuotaLimit) TableName() string { return q.queueQuotaLimitDo.TableName() }

func (q queueQuotaLimit) Alias() string { return q.queueQuotaLimitDo.Alias() }

func (q queueQuotaLimit) Columns(cols ...field.Expr) gen.Columns {
	return q.queueQuotaLimitDo.Columns(cols...)
}

func (q *queueQuotaLimit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := q.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (q *queueQuotaLimit) fillFieldMap() {
	q.fieldMap = make(map[string]field.Expr, 6)
	q.fieldMap["id"] = q.ID
	q.fieldMap["created_at"] = q.CreatedAt
	q.fieldMap["updated_at"] = q.UpdatedAt
	q.fieldMap["deleted_at"] = q.DeletedAt
	q.fieldMap["name"] = q.Name
	q.fieldMap["quota"] = q.Quota
}

func (q queueQuotaLimit) clone(db *gorm.DB) queueQuotaLimit {
	q.queueQuotaLimitDo.ReplaceConnPool(db.Statement.ConnPool)
	return q
}

func (q queueQuotaLimit) replaceDB(db *gorm.DB) queueQuotaLimit {
	q.queueQuotaLimitDo.ReplaceDB(db)
	return q
}

type queueQuotaLimitDo struct{ gen.DO }

type IQueueQuotaLimitDo interface {
	gen.SubQuery
	Debug() IQueueQuotaLimitDo
	WithContext(ctx context.Context) IQueueQuotaLimitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IQueueQuotaLimitDo
	WriteDB() IQueueQuotaLimitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IQueueQuotaLimitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IQueueQuotaLimitDo
	Not(conds ...gen.Condition) IQueueQuotaLimitDo
	Or(conds ...gen.Condition) IQueueQuotaLimitDo
	Select(conds ...field.Expr) IQueueQuotaLimitDo
	Where(conds ...gen.Condition) IQueueQuotaLimitDo
	Order(conds ...field.Expr) IQueueQuotaLimitDo
	Distinct(cols ...field.Expr) IQueueQuotaLimitDo
	Omit(cols ...field.Expr) IQueueQuotaLimitDo
	Join(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo
	Group(cols ...field.Expr) IQueueQuotaLimitDo
	Having(conds ...gen.Condition) IQueueQuotaLimitDo
	Limit(limit int) IQueueQuotaLimitDo
	Offset(offset int) IQueueQuotaLimitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IQueueQuotaLimitDo
	Unscoped() IQueueQuotaLimitDo
	Create(values ...*model.QueueQuotaLimit) error
	CreateInBatches(values []*model.QueueQuotaLimit, batchSize int) error
	Save(values ...*model.QueueQuotaLimit) error
	First() (*model.QueueQuotaLimit, error)
	Take() (*model.QueueQuotaLimit, error)
	Last() (*model.QueueQuotaLimit, error)
	Find() ([]*model.QueueQuotaLimit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QueueQuotaLimit, err error)
	FindInBatches(result *[]*model.QueueQuotaLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.QueueQuotaLimit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IQueueQuotaLimitDo
	Assign(attrs ...field.AssignExpr) IQueueQuotaLimitDo
	Joins(fields ...field.RelationField) IQueueQuotaLimitDo
	Preload(fields ...field.RelationField) IQueueQuotaLimitDo
	FirstOrInit() (*model.QueueQuotaLimit, error)
	FirstOrCreate() (*model.QueueQuotaLimit, error)
	FindByPage(offset int, limit int) (result []*model.QueueQuotaLimit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IQueueQuotaLimitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (q queueQuotaLimitDo) Debug() IQueueQuotaLimitDo {
	return q.withDO(q.DO.Debug())
}

func (q queueQuotaLimitDo) WithContext(ctx context.Context) IQueueQuotaLimitDo {
	return q.withDO(q.DO.WithContext(ctx))
}

func (q queueQuotaLimitDo) ReadDB() IQueueQuotaLimitDo {
	return q.Clauses(dbresolver.Read)
}

func (q queueQuotaLimitDo) WriteDB() IQueueQuotaLimitDo {
	return q.Clauses(dbresolver.Write)
}

func (q queueQuotaLimitDo) Session(config *gorm.Session) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Session(config))
}

func (q queueQuotaLimitDo) Clauses(conds ...clause.Expression) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Clauses(conds...))
}

func (q queueQuotaLimitDo) Returning(value interface{}, columns ...string) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Returning(value, columns...))
}

func (q queueQuotaLimitDo) Not(conds ...gen.Condition) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Not(conds...))
}

func (q queueQuotaLimitDo) Or(conds ...gen.Condition) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Or(conds...))
}

func (q queueQuotaLimitDo) Select(conds ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Select(conds...))
}

func (q queueQuotaLimitDo) Where(conds ...gen.Condition) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Where(conds...))
}

func (q queueQuotaLimitDo) Order(conds ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Order(conds...))
}

func (q queueQuotaLimitDo) Distinct(cols ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Distinct(cols...))
}

func (q queueQuotaLimitDo) Omit(cols ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Omit(cols...))
}

func (q queueQuotaLimitDo) Join(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Join(table, on...))
}

func (q queueQuotaLimitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.LeftJoin(table, on...))
}

func (q queueQuotaLimitDo) RightJoin(table schema.Tabler, on ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.RightJoin(table, on...))
}

func (q queueQuotaLimitDo) Group(cols ...field.Expr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Group(cols...))
}

func (q queueQuotaLimitDo) Having(conds ...gen.Condition) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Having(conds...))
}

func (q queueQuotaLimitDo) Limit(limit int) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Limit(limit))
}

func (q queueQuotaLimitDo) Offset(offset int) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Offset(offset))
}

func (q queueQuotaLimitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Scopes(funcs...))
}

func (q queueQuotaLimitDo) Unscoped() IQueueQuotaLimitDo {
	return q.withDO(q.DO.Unscoped())
}

func (q queueQuotaLimitDo) Create(values ...*model.QueueQuotaLimit) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Create(values)
}

func (q queueQuotaLimitDo) CreateInBatches(values []*model.QueueQuotaLimit, batchSize int) error {
	return q.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (q queueQuotaLimitDo) Save(values ...*model.QueueQuotaLimit) error {
	if len(values) == 0 {
		return nil
	}
	return q.DO.Save(values)
}

func (q queueQuotaLimitDo) First() (*model.QueueQuotaLimit, error) {
	if result, err := q.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.QueueQuotaLimit), nil
	}
}

func (q queueQuotaLimitDo) Take() (*model.QueueQuotaLimit, error) {
	if result, err := q.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.QueueQuotaLimit), nil
	}
}

func (q queueQuotaLimitDo) Last() (*model.QueueQuotaLimit, error) {
	if result, err := q.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.QueueQuotaLimit), nil
	}
}

func (q queueQuotaLimitDo) Find() ([]*model.QueueQuotaLimit, error) {
	result, err := q.DO.Find()
	return result.([]*model.QueueQuotaLimit), err
}

func (q queueQuotaLimitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.QueueQuotaLimit, err error) {
	buf := make([]*model.QueueQuotaLimit, 0, batchSize)
	err = q.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (q queueQuotaLimitDo) FindInBatches(result *[]*model.QueueQuotaLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return q.DO.FindInBatches(result, batchSize, fc)
}

func (q queueQuotaLimitDo) Attrs(attrs ...field.AssignExpr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Attrs(attrs...))
}

func (q queueQuotaLimitDo) Assign(attrs ...field.AssignExpr) IQueueQuotaLimitDo {
	return q.withDO(q.DO.Assign(attrs...))
}

func (q queueQuotaLimitDo) Joins(fields ...field.RelationField) IQueueQuotaLimitDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Joins(_f))
	}
	return &q
}

func (q queueQuotaLimitDo) Preload(fields ...field.RelationField) IQueueQuotaLimitDo {
	for _, _f := range fields {
		q = *q.withDO(q.DO.Preload(_f))
	}
	return &q
}

func (q queueQuotaLimitDo) FirstOrInit() (*model.QueueQuotaLimit, error) {
	if result, err := q.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.QueueQuotaLimit), nil
	}
}

func (q queueQuotaLimitDo) FirstOrCreate() (*model.QueueQuotaLimit, error) {
	if result, err := q.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.QueueQuotaLimit), nil
	}
}

func (q queueQuotaLimitDo) FindByPage(offset int, limit int) (result []*model.QueueQuotaLimit, count int64, err error) {
	result, err = q.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = q.Offset(-1).Limit(-1).Count()
	return
}

func (q queueQuotaLimitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = q.Count()
	if err != nil {
		return
	}

	err = q.Offset(offset).Limit(limit).Scan(result)
	return
}

func (q queueQuotaLimitDo) Scan(result interface{}) (err error) {
	return q.DO.Scan(result)
}

func (q queueQuotaLimitDo) Delete(models ...*model.QueueQuotaLimit) (result gen.ResultInfo, err error) {
	return q.DO.Delete(models)
}

func (q *queueQuotaLimitDo) withDO(do gen.Dao) *queueQuotaLimitDo {
	q.DO = *do.(*gen.DO)
	return q
}
