// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newUserModelDownload(db *gorm.DB, opts ...gen.DOOption) userModelDownload {
	_userModelDownload := userModelDownload{}

	_userModelDownload.userModelDownloadDo.UseDB(db, opts...)
	_userModelDownload.userModelDownloadDo.UseModel(&model.UserModelDownload{})

	tableName := _userModelDownload.userModelDownloadDo.TableName()
	_userModelDownload.ALL = field.NewAsterisk(tableName)
	_userModelDownload.ID = field.NewUint(tableName, "id")
	_userModelDownload.UserID = field.NewUint(tableName, "user_id")
	_userModelDownload.ModelDownloadID = field.NewUint(tableName, "model_download_id")
	_userModelDownload.CreatedAt = field.NewTime(tableName, "created_at")
	_userModelDownload.User = userModelDownloadBelongsToUser{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("User", "model.User"),
		UserAccounts: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.UserAccounts", "model.UserAccount"),
		},
		UserDatasets: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("User.UserDatasets", "model.UserDataset"),
		},
	}

	_userModelDownload.ModelDownload = userModelDownloadBelongsToModelDownload{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("ModelDownload", "model.ModelDownload"),
		Creator: struct {
			field.RelationField
		}{
			RelationField: field.NewRelation("ModelDownload.Creator", "model.User"),
		},
	}

	_userModelDownload.fillFieldMap()

	return _userModelDownload
}

type userModelDownload struct {
	userModelDownloadDo userModelDownloadDo

	ALL             field.Asterisk
	ID              field.Uint
	UserID          field.Uint // 用户ID
	ModelDownloadID field.Uint // 下载任务ID
	CreatedAt       field.Time // 用户添加此下载的时间
	User            userModelDownloadBelongsToUser

	ModelDownload userModelDownloadBelongsToModelDownload

	fieldMap map[string]field.Expr
}

func (u userModelDownload) Table(newTableName string) *userModelDownload {
	u.userModelDownloadDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userModelDownload) As(alias string) *userModelDownload {
	u.userModelDownloadDo.DO = *(u.userModelDownloadDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userModelDownload) updateTableName(table string) *userModelDownload {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.UserID = field.NewUint(table, "user_id")
	u.ModelDownloadID = field.NewUint(table, "model_download_id")
	u.CreatedAt = field.NewTime(table, "created_at")

	u.fillFieldMap()

	return u
}

func (u *userModelDownload) WithContext(ctx context.Context) IUserModelDownloadDo {
	return u.userModelDownloadDo.WithContext(ctx)
}

func (u userModelDownload) TableName() string { return u.userModelDownloadDo.TableName() }

func (u userModelDownload) Alias() string { return u.userModelDownloadDo.Alias() }

func (u userModelDownload) Columns(cols ...field.Expr) gen.Columns {
	return u.userModelDownloadDo.Columns(cols...)
}

func (u *userModelDownload) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userModelDownload) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["model_download_id"] = u.ModelDownloadID
	u.fieldMap["created_at"] = u.CreatedAt

}

func (u userModelDownload) clone(db *gorm.DB) userModelDownload {
	u.userModelDownloadDo.ReplaceConnPool(db.Statement.ConnPool)
	u.User.db = db.Session(&gorm.Session{Initialized: true})
	u.User.db.Statement.ConnPool = db.Statement.ConnPool
	u.ModelDownload.db = db.Session(&gorm.Session{Initialized: true})
	u.ModelDownload.db.Statement.ConnPool = db.Statement.ConnPool
	return u
}

func (u userModelDownload) replaceDB(db *gorm.DB) userModelDownload {
	u.userModelDownloadDo.ReplaceDB(db)
	u.User.db = db.Session(&gorm.Session{})
	u.ModelDownload.db = db.Session(&gorm.Session{})
	return u
}

type userModelDownloadBelongsToUser struct {
	db *gorm.DB

	field.RelationField

	UserAccounts struct {
		field.RelationField
	}
	UserDatasets struct {
		field.RelationField
	}
}

func (a userModelDownloadBelongsToUser) Where(conds ...field.Expr) *userModelDownloadBelongsToUser {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userModelDownloadBelongsToUser) WithContext(ctx context.Context) *userModelDownloadBelongsToUser {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userModelDownloadBelongsToUser) Session(session *gorm.Session) *userModelDownloadBelongsToUser {
	a.db = a.db.Session(session)
	return &a
}

func (a userModelDownloadBelongsToUser) Model(m *model.UserModelDownload) *userModelDownloadBelongsToUserTx {
	return &userModelDownloadBelongsToUserTx{a.db.Model(m).Association(a.Name())}
}

func (a userModelDownloadBelongsToUser) Unscoped() *userModelDownloadBelongsToUser {
	a.db = a.db.Unscoped()
	return &a
}

type userModelDownloadBelongsToUserTx struct{ tx *gorm.Association }

func (a userModelDownloadBelongsToUserTx) Find() (result *model.User, err error) {
	return result, a.tx.Find(&result)
}

func (a userModelDownloadBelongsToUserTx) Append(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userModelDownloadBelongsToUserTx) Replace(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userModelDownloadBelongsToUserTx) Delete(values ...*model.User) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userModelDownloadBelongsToUserTx) Clear() error {
	return a.tx.Clear()
}

func (a userModelDownloadBelongsToUserTx) Count() int64 {
	return a.tx.Count()
}

func (a userModelDownloadBelongsToUserTx) Unscoped() *userModelDownloadBelongsToUserTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userModelDownloadBelongsToModelDownload struct {
	db *gorm.DB

	field.RelationField

	Creator struct {
		field.RelationField
	}
}

func (a userModelDownloadBelongsToModelDownload) Where(conds ...field.Expr) *userModelDownloadBelongsToModelDownload {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a userModelDownloadBelongsToModelDownload) WithContext(ctx context.Context) *userModelDownloadBelongsToModelDownload {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a userModelDownloadBelongsToModelDownload) Session(session *gorm.Session) *userModelDownloadBelongsToModelDownload {
	a.db = a.db.Session(session)
	return &a
}

func (a userModelDownloadBelongsToModelDownload) Model(m *model.UserModelDownload) *userModelDownloadBelongsToModelDownloadTx {
	return &userModelDownloadBelongsToModelDownloadTx{a.db.Model(m).Association(a.Name())}
}

func (a userModelDownloadBelongsToModelDownload) Unscoped() *userModelDownloadBelongsToModelDownload {
	a.db = a.db.Unscoped()
	return &a
}

type userModelDownloadBelongsToModelDownloadTx struct{ tx *gorm.Association }

func (a userModelDownloadBelongsToModelDownloadTx) Find() (result *model.ModelDownload, err error) {
	return result, a.tx.Find(&result)
}

func (a userModelDownloadBelongsToModelDownloadTx) Append(values ...*model.ModelDownload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a userModelDownloadBelongsToModelDownloadTx) Replace(values ...*model.ModelDownload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a userModelDownloadBelongsToModelDownloadTx) Delete(values ...*model.ModelDownload) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a userModelDownloadBelongsToModelDownloadTx) Clear() error {
	return a.tx.Clear()
}

func (a userModelDownloadBelongsToModelDownloadTx) Count() int64 {
	return a.tx.Count()
}

func (a userModelDownloadBelongsToModelDownloadTx) Unscoped() *userModelDownloadBelongsToModelDownloadTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type userModelDownloadDo struct{ gen.DO }

type IUserModelDownloadDo interface {
	gen.SubQuery
	Debug() IUserModelDownloadDo
	WithContext(ctx context.Context) IUserModelDownloadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserModelDownloadDo
	WriteDB() IUserModelDownloadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserModelDownloadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserModelDownloadDo
	Not(conds ...gen.Condition) IUserModelDownloadDo
	Or(conds ...gen.Condition) IUserModelDownloadDo
	Select(conds ...field.Expr) IUserModelDownloadDo
	Where(conds ...gen.Condition) IUserModelDownloadDo
	Order(conds ...field.Expr) IUserModelDownloadDo
	Distinct(cols ...field.Expr) IUserModelDownloadDo
	Omit(cols ...field.Expr) IUserModelDownloadDo
	Join(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo
	Group(cols ...field.Expr) IUserModelDownloadDo
	Having(conds ...gen.Condition) IUserModelDownloadDo
	Limit(limit int) IUserModelDownloadDo
	Offset(offset int) IUserModelDownloadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserModelDownloadDo
	Unscoped() IUserModelDownloadDo
	Create(values ...*model.UserModelDownload) error
	CreateInBatches(values []*model.UserModelDownload, batchSize int) error
	Save(values ...*model.UserModelDownload) error
	First() (*model.UserModelDownload, error)
	Take() (*model.UserModelDownload, error)
	Last() (*model.UserModelDownload, error)
	Find() ([]*model.UserModelDownload, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserModelDownload, err error)
	FindInBatches(result *[]*model.UserModelDownload, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserModelDownload) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserModelDownloadDo
	Assign(attrs ...field.AssignExpr) IUserModelDownloadDo
	Joins(fields ...field.RelationField) IUserModelDownloadDo
	Preload(fields ...field.RelationField) IUserModelDownloadDo
	FirstOrInit() (*model.UserModelDownload, error)
	FirstOrCreate() (*model.UserModelDownload, error)
	FindByPage(offset int, limit int) (result []*model.UserModelDownload, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserModelDownloadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userModelDownloadDo) Debug() IUserModelDownloadDo {
	return u.withDO(u.DO.Debug())
}

func (u userModelDownloadDo) WithContext(ctx context.Context) IUserModelDownloadDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userModelDownloadDo) ReadDB() IUserModelDownloadDo {
	return u.Clauses(dbresolver.Read)
}

func (u userModelDownloadDo) WriteDB() IUserModelDownloadDo {
	return u.Clauses(dbresolver.Write)
}

func (u userModelDownloadDo) Session(config *gorm.Session) IUserModelDownloadDo {
	return u.withDO(u.DO.Session(config))
}

func (u userModelDownloadDo) Clauses(conds ...clause.Expression) IUserModelDownloadDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userModelDownloadDo) Returning(value interface{}, columns ...string) IUserModelDownloadDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userModelDownloadDo) Not(conds ...gen.Condition) IUserModelDownloadDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userModelDownloadDo) Or(conds ...gen.Condition) IUserModelDownloadDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userModelDownloadDo) Select(conds ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userModelDownloadDo) Where(conds ...gen.Condition) IUserModelDownloadDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userModelDownloadDo) Order(conds ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userModelDownloadDo) Distinct(cols ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userModelDownloadDo) Omit(cols ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userModelDownloadDo) Join(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userModelDownloadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userModelDownloadDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userModelDownloadDo) Group(cols ...field.Expr) IUserModelDownloadDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userModelDownloadDo) Having(conds ...gen.Condition) IUserModelDownloadDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userModelDownloadDo) Limit(limit int) IUserModelDownloadDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userModelDownloadDo) Offset(offset int) IUserModelDownloadDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userModelDownloadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserModelDownloadDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userModelDownloadDo) Unscoped() IUserModelDownloadDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userModelDownloadDo) Create(values ...*model.UserModelDownload) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userModelDownloadDo) CreateInBatches(values []*model.UserModelDownload, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userModelDownloadDo) Save(values ...*model.UserModelDownload) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userModelDownloadDo) First() (*model.UserModelDownload, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModelDownload), nil
	}
}

func (u userModelDownloadDo) Take() (*model.UserModelDownload, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModelDownload), nil
	}
}

func (u userModelDownloadDo) Last() (*model.UserModelDownload, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModelDownload), nil
	}
}

func (u userModelDownloadDo) Find() ([]*model.UserModelDownload, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserModelDownload), err
}

func (u userModelDownloadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserModelDownload, err error) {
	buf := make([]*model.UserModelDownload, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userModelDownloadDo) FindInBatches(result *[]*model.UserModelDownload, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userModelDownloadDo) Attrs(attrs ...field.AssignExpr) IUserModelDownloadDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userModelDownloadDo) Assign(attrs ...field.AssignExpr) IUserModelDownloadDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userModelDownloadDo) Joins(fields ...field.RelationField) IUserModelDownloadDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userModelDownloadDo) Preload(fields ...field.RelationField) IUserModelDownloadDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userModelDownloadDo) FirstOrInit() (*model.UserModelDownload, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModelDownload), nil
	}
}

func (u userModelDownloadDo) FirstOrCreate() (*model.UserModelDownload, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserModelDownload), nil
	}
}

func (u userModelDownloadDo) FindByPage(offset int, limit int) (result []*model.UserModelDownload, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userModelDownloadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userModelDownloadDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userModelDownloadDo) Delete(models ...*model.UserModelDownload) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userModelDownloadDo) withDO(do gen.Dao) *userModelDownloadDo {
	u.DO = *do.(*gen.DO)
	return u
}
