// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/raids-lab/crater/dao/model"
)

func newUserBanRecord(db *gorm.DB, opts ...gen.DOOption) userBanRecord {
	_userBanRecord := userBanRecord{}

	_userBanRecord.userBanRecordDo.UseDB(db, opts...)
	_userBanRecord.userBanRecordDo.UseModel(&model.UserBanRecord{})

	tableName := _userBanRecord.userBanRecordDo.TableName()
	_userBanRecord.ALL = field.NewAsterisk(tableName)
	_userBanRecord.ID = field.NewUint(tableName, "id")
	_userBanRecord.CreatedAt = field.NewTime(tableName, "created_at")
	_userBanRecord.UserID = field.NewUint(tableName, "user_id")
	_userBanRecord.UserName = field.NewString(tableName, "user_name")
	_userBanRecord.OperatorID = field.NewUint(tableName, "operator_id")
	_userBanRecord.OperatorName = field.NewString(tableName, "operator_name")
	_userBanRecord.Action = field.NewString(tableName, "action")
	_userBanRecord.Reason = field.NewString(tableName, "reason")

	_userBanRecord.fillFieldMap()

	return _userBanRecord
}

type userBanRecord struct {
	userBanRecordDo userBanRecordDo

	ALL          field.Asterisk
	ID           field.Uint
	CreatedAt    field.Time
	UserID       field.Uint
	UserName     field.String
	OperatorID   field.Uint
	OperatorName field.String
	Action       field.String
	Reason       field.String

	fieldMap map[string]field.Expr
}

func (u userBanRecord) Table(newTableName string) *userBanRecord {
	u.userBanRecordDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u userBanRecord) As(alias string) *userBanRecord {
	u.userBanRecordDo.DO = *(u.userBanRecordDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *userBanRecord) updateTableName(table string) *userBanRecord {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewUint(table, "id")
	u.CreatedAt = field.NewTime(table, "created_at")
	u.UserID = field.NewUint(table, "user_id")
	u.UserName = field.NewString(table, "user_name")
	u.OperatorID = field.NewUint(table, "operator_id")
	u.OperatorName = field.NewString(table, "operator_name")
	u.Action = field.NewString(table, "action")
	u.Reason = field.NewString(table, "reason")

	u.fillFieldMap()

	return u
}

func (u *userBanRecord) WithContext(ctx context.Context) IUserBanRecordDo {
	return u.userBanRecordDo.WithContext(ctx)
}

func (u userBanRecord) TableName() string { return u.userBanRecordDo.TableName() }

func (u userBanRecord) Alias() string { return u.userBanRecordDo.Alias() }

func (u userBanRecord) Columns(cols ...field.Expr) gen.Columns {
	return u.userBanRecordDo.Columns(cols...)
}

func (u *userBanRecord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *userBanRecord) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 8)
	u.fieldMap["id"] = u.ID
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["user_id"] = u.UserID
	u.fieldMap["user_name"] = u.UserName
	u.fieldMap["operator_id"] = u.OperatorID
	u.fieldMap["operator_name"] = u.OperatorName
	u.fieldMap["action"] = u.Action
	u.fieldMap["reason"] = u.Reason
}

func (u userBanRecord) clone(db *gorm.DB) userBanRecord {
	u.userBanRecordDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u userBanRecord) replaceDB(db *gorm.DB) userBanRecord {
	u.userBanRecordDo.ReplaceDB(db)
	return u
}

type userBanRecordDo struct{ gen.DO }

type IUserBanRecordDo interface {
	gen.SubQuery
	Debug() IUserBanRecordDo
	WithContext(ctx context.Context) IUserBanRecordDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUserBanRecordDo
	WriteDB() IUserBanRecordDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUserBanRecordDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUserBanRecordDo
	Not(conds ...gen.Condition) IUserBanRecordDo
	Or(conds ...gen.Condition) IUserBanRecordDo
	Select(conds ...field.Expr) IUserBanRecordDo
	Where(conds ...gen.Condition) IUserBanRecordDo
	Order(conds ...field.Expr) IUserBanRecordDo
	Distinct(cols ...field.Expr) IUserBanRecordDo
	Omit(cols ...field.Expr) IUserBanRecordDo
	Join(table schema.Tabler, on ...field.Expr) IUserBanRecordDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUserBanRecordDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUserBanRecordDo
	Group(cols ...field.Expr) IUserBanRecordDo
	Having(conds ...gen.Condition) IUserBanRecordDo
	Limit(limit int) IUserBanRecordDo
	Offset(offset int) IUserBanRecordDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBanRecordDo
	Unscoped() IUserBanRecordDo
	Create(values ...*model.UserBanRecord) error
	CreateInBatches(values []*model.UserBanRecord, batchSize int) error
	Save(values ...*model.UserBanRecord) error
	First() (*model.UserBanRecord, error)
	Take() (*model.UserBanRecord, error)
	Last() (*model.UserBanRecord, error)
	Find() ([]*model.UserBanRecord, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBanRecord, err error)
	FindInBatches(result *[]*model.UserBanRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.UserBanRecord) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUserBanRecordDo
	Assign(attrs ...field.AssignExpr) IUserBanRecordDo
	Joins(fields ...field.RelationField) IUserBanRecordDo
	Preload(fields ...field.RelationField) IUserBanRecordDo
	FirstOrInit() (*model.UserBanRecord, error)
	FirstOrCreate() (*model.UserBanRecord, error)
	FindByPage(offset int, limit int) (result []*model.UserBanRecord, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUserBanRecordDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u userBanRecordDo) Debug() IUserBanRecordDo {
	return u.withDO(u.DO.Debug())
}

func (u userBanRecordDo) WithContext(ctx context.Context) IUserBanRecordDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u userBanRecordDo) ReadDB() IUserBanRecordDo {
	return u.Clauses(dbresolver.Read)
}

func (u userBanRecordDo) WriteDB() IUserBanRecordDo {
	return u.Clauses(dbresolver.Write)
}

func (u userBanRecordDo) Session(config *gorm.Session) IUserBanRecordDo {
	return u.withDO(u.DO.Session(config))
}

func (u userBanRecordDo) Clauses(conds ...clause.Expression) IUserBanRecordDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u userBanRecordDo) Returning(value interface{}, columns ...string) IUserBanRecordDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u userBanRecordDo) Not(conds ...gen.Condition) IUserBanRecordDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u userBanRecordDo) Or(conds ...gen.Condition) IUserBanRecordDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u userBanRecordDo) Select(conds ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u userBanRecordDo) Where(conds ...gen.Condition) IUserBanRecordDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u userBanRecordDo) Order(conds ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u userBanRecordDo) Distinct(cols ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u userBanRecordDo) Omit(cols ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u userBanRecordDo) Join(table schema.Tabler, on ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u userBanRecordDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u userBanRecordDo) RightJoin(table schema.Tabler, on ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u userBanRecordDo) Group(cols ...field.Expr) IUserBanRecordDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u userBanRecordDo) Having(conds ...gen.Condition) IUserBanRecordDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u userBanRecordDo) Limit(limit int) IUserBanRecordDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u userBanRecordDo) Offset(offset int) IUserBanRecordDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u userBanRecordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUserBanRecordDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u userBanRecordDo) Unscoped() IUserBanRecordDo {
	return u.withDO(u.DO.Unscoped())
}

func (u userBanRecordDo) Create(values ...*model.UserBanRecord) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u userBanRecordDo) CreateInBatches(values []*model.UserBanRecord, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u userBanRecordDo) Save(values ...*model.UserBanRecord) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u userBanRecordDo) First() (*model.UserBanRecord, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBanRecord), nil
	}
}

func (u userBanRecordDo) Take() (*model.UserBanRecord, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBanRecord), nil
	}
}

func (u userBanRecordDo) Last() (*model.UserBanRecord, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBanRecord), nil
	}
}

func (u userBanRecordDo) Find() ([]*model.UserBanRecord, error) {
	result, err := u.DO.Find()
	return result.([]*model.UserBanRecord), err
}

func (u userBanRecordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.UserBanRecord, err error) {
	buf := make([]*model.UserBanRecord, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u userBanRecordDo) FindInBatches(result *[]*model.UserBanRecord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u userBanRecordDo) Attrs(attrs ...field.AssignExpr) IUserBanRecordDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u userBanRecordDo) Assign(attrs ...field.AssignExpr) IUserBanRecordDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u userBanRecordDo) Joins(fields ...field.RelationField) IUserBanRecordDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u userBanRecordDo) Preload(fields ...field.RelationField) IUserBanRecordDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u userBanRecordDo) FirstOrInit() (*model.UserBanRecord, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBanRecord), nil
	}
}

func (u userBanRecordDo) FirstOrCreate() (*model.UserBanRecord, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.UserBanRecord), nil
	}
}

func (u userBanRecordDo) FindByPage(offset int, limit int) (result []*model.UserBanRecord, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u userBanRecordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u userBanRecordDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u userBanRecordDo) Delete(models ...*model.UserBanRecord) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *userBanRecordDo) withDO(do gen.Dao) *userBanRecordDo {
	u.DO = *do.(*gen.DO)
	return u
}
