# This file is used to deploy the backend service to the k8s cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crater-backend
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespaces.job }}
  name: crater-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crater-rolebinding
  namespace: {{ .Values.namespaces.job }}
subjects:
  - kind: ServiceAccount
    name: crater-backend
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: crater-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crater-viewer
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["scheduling.volcano.sh"]
    resources: ["queues"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crater-viewer-binding
subjects:
  - kind: ServiceAccount
    name: crater-backend
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: crater-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crater-cronjob-admin
  namespace: crater
rules:
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crater-cronjob-admin-binding
  namespace: crater
subjects:
  - kind: ServiceAccount
    name: crater-backend
    namespace: crater
roleRef:
  kind: Role
  name: crater-cronjob-admin
  apiGroup: rbac.authorization.k8s.io
