# web backend ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crater-web-backend-ingress
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.global.host | default .Values.web.ingress.host }}
      secretName: {{ .Values.global.tlsSecretName | default "crater-tls-secret" }}
  rules:
    - host: {{ .Values.global.host | default .Values.web.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: crater-web-backend-svc
                port:
                  number: 80
            path: /api/(?!(ss/))(.*) 
            pathType: Prefix
