apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-server-ingress
  namespace: {{ .Values.namespaces.job }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: crater-tls-secret
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /api/ss
            pathType: Prefix
            backend:
              service:
                name: webdav-service
                port:
                  number: 7320
