apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: storage-server-ingress
  namespace: {{ .Values.global.namespace | default .Values.backendConfig.workspace.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "1000m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.global.host | default .Values.web.ingress.host }}
      secretName: {{ .Values.global.tlsSecretName | default "crater-tls-secret" }}
  rules:
    - host: {{ .Values.global.host | default .Values.web.ingress.host }}
      http:
        paths:
          - path: /api/ss
            pathType: Prefix
            backend:
              service:
                name: webdav-service
                port:
                  number: 7320
