# web backend ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crater-backend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: crater-tls-secret
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: crater-backend-svc
                port:
                  number: 80
            path: /api
            pathType: Prefix
