apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crater-grafana-proxy-ingress
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: ALLOW-FROM {{ .Values.web.grafana.ancestor }}";
      more_set_headers "Content-Security-Policy: frame-ancestors {{ .Values.web.grafana.ancestor }}";
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.global.grafanaHost | default .Values.web.grafana.host }}
      secretName: {{ .Values.global.tlsSecretName | default "crater-tls-secret" }}
  rules:
    - host: {{ .Values.global.grafanaHost | default .Values.web.grafana.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-proxy
                port:
                  number: 80
