{{- if .Values.tls.base.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tlsSecretName | default "crater-tls-secret" }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.base.cert | b64enc }}
  tls.key: {{ .Values.tls.base.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tlsSecretName | default "crater-tls-secret" }}
  namespace: {{ .Values.global.namespace | default .Values.backendConfig.workspace.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.base.cert | b64enc }}
  tls.key: {{ .Values.tls.base.key | b64enc }}
{{- end }}
---
{{- if .Values.tls.forward.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tlsForwardSecretName | default "crater-tls-forward-secret" }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.forward.cert | b64enc }}
  tls.key: {{ .Values.tls.forward.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.tlsForwardSecretName | default "crater-tls-forward-secret" }}
  namespace: {{ .Values.global.namespace | default .Values.backendConfig.workspace.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.forward.cert | b64enc }}
  tls.key: {{ .Values.tls.forward.key | b64enc }}
{{- end }}