{{- if .Values.tls.base.create }}
apiVersion: v1
kind: Secret
metadata:
  name: crater-tls-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.base.cert | b64enc }}
  tls.key: {{ .Values.tls.base.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: crater-tls-secret
  namespace: {{ .Values.namespaces.job }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.base.cert | b64enc }}
  tls.key: {{ .Values.tls.base.key | b64enc }}
{{- end }}
---
{{- if .Values.tls.forward.create }}
apiVersion: v1
kind: Secret
metadata:
  name: crater-tls-forward-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.forward.cert | b64enc }}
  tls.key: {{ .Values.tls.forward.key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: crater-tls-forward-secret
  namespace: {{ .Values.namespaces.job }}
  annotations:
    "helm.sh/resource-policy": keep
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.forward.cert | b64enc }}
  tls.key: {{ .Values.tls.forward.key | b64enc }}
{{- end }}