apiVersion: v1
kind: ConfigMap
metadata:
  name: crater-cronjob-config
  namespace: {{ .Release.Namespace }}
  labels:
    crater.raids-lab.io/component: cronjob
data:
  USERNAME: {{ .Values.firstUser.username }}
  PASSWORD: {{ .Values.firstUser.password }}
  HOST: crater-backend-svc.{{ .Release.Namespace }}.svc.cluster.local
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crater-cronjob-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    crater.raids-lab.io/component: cronjob
data:
  token.sh: |-
    #!/bin/sh
    response=$(curl -s -X POST \
      "http://${HOST}/api/auth/login" \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -d "{
      \"auth\": \"normal\",
      \"password\": \"${PASSWORD}\",
      \"username\": \"${USERNAME}\"
    }")

    accessToken=$(echo "$response" | jq -r '.data.accessToken')
    echo "$accessToken"
  
  clean-long-time-job.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理长时间任务..."
    curl -X DELETE \
      "http://${HOST}/api/v1/admin/operations/cleanup?batchDays=${BATCH_DAYS}&interactiveDays=${INTERACTIVE_DAYS}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"

  clean-low-gpu-util-job.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理GPU低利用率任务..."
    curl -X DELETE \
      "http://${HOST}/api/v1/admin/operations/auto?timeRange=${TIME_RANGE}&waitTime=${WAIT_TIME}&util=${UTIL}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"

  clean-waiting-jupyter.sh: |-
    #!/bin/sh
    accessToken=$(sh /scripts/token.sh)

    echo "清理等待的Jupyter任务..."
    curl -X DELETE \
      "http://${HOST}/api/v1/admin/operations/waiting/jupyter?waitMinitues=${JUPYTER_WAIT_MINUTES}" \
      -H 'accept: application/json' \
      -H "Authorization: Bearer ${accessToken}"
  backup.sh: |-
    #!/bin/bash
    set -euo pipefail

    BACKUP_DIR="${BACKUP_DIR:-/backups}"
    RETENTION_COUNT="${RETENTION_COUNT:-7}"
    TIMEZONE="${TZ:-Asia/Shanghai}"

    export TZ="${TIMEZONE}"

    DB_HOST="${DB_HOST}"
    DB_PORT="${DB_PORT}"
    DB_NAME="${DB_NAME}"
    DB_USER="${DB_USER}"
    DB_PASS="${DB_PASS}"

    BACKUP_FILE="${BACKUP_DIR}/crater_$(date +%Y%m%d_%H%M%S).dump"
    export PGPASSWORD="${DB_PASS}"
    echo "$(date): Starting backup to ${BACKUP_FILE}"
    pg_dump -v \
      -h "${DB_HOST}" \
      -p "${DB_PORT}" \
      -U "${DB_USER}" \
      -d "${DB_NAME}" \
      -f "${BACKUP_FILE}"

    if [ -s "${BACKUP_FILE}" ]; then
      echo "$(date): Backup succeeded: $(ls -lh "${BACKUP_FILE}")"
    else
      echo "$(date): Backup FAILED" >&2
      exit 1
    fi

    # 按时间排序，保留最新的 N 个文件
    echo "$(date): Cleaning up old backups, keeping latest ${RETENTION_COUNT} files"
    ls -t "${BACKUP_DIR}"/*.dump | tail -n +$((RETENTION_COUNT + 1)) | xargs -r rm -f

    echo "$(date): Backup Cleanup completed"