#!/bin/sh
if ! (cd backend && make lint); then
    echo "Backend Lint fail!"
    exit 1
fi

if ! (cd frontend && make lint); then
    echo "Frontend Lint fail!"
    exit 1
fi

# generate swagger
if ! (cd backend && make docs); then
    echo "Make docs fail!"
    exit 1
fi

echo "Lint success!"
exit 0