// This file is generated by generator.py
// Please do not modify this file manually

export type ErrorCode = number

export const LEGACY_BAD_REQUEST_ERROR_GROUP: ErrorCode = 400
export const LEGACY_AUTH_ERROR_GROUP: ErrorCode = 401
export const LEGACY_FORBIDDEN_ERROR_GROUP: ErrorCode = 403
export const LEGACY_NOT_FOUND_ERROR_GROUP: ErrorCode = 404
export const LEGACY_INTERNAL_ERROR_GROUP: ErrorCode = 500

// 400xx - Bad Request
export const LEGACY_ERROR_INVALID_REQUEST: ErrorCode = 40001

// 401xx - Auth
export const LEGACY_ERROR_TOKEN_EXPIRED: ErrorCode = 40101
export const LEGACY_ERROR_TOKEN_INVALID: ErrorCode = 40102
export const LEGACY_ERROR_INVALID_CREDENTIALS: ErrorCode = 40111
export const LEGACY_ERROR_LDAP_ERROR: ErrorCode = 40112
export const LEGACY_ERROR_LDAP_USER_NOT_FOUND: ErrorCode = 40113
export const LEGACY_ERROR_LEGACY_TOKEN_NOT_SUPPORTED: ErrorCode = 40114
export const LEGACY_ERROR_MUST_REGISTER: ErrorCode = 40121

// 403xx - Forbidden
export const LEGACY_ERROR_USER_NOT_ALLOWED: ErrorCode = 40301
export const LEGACY_ERROR_USER_EMAIL_NOT_VERIFIED: ErrorCode = 40302

// 404xx - Not Found
export const LEGACY_ERROR_SERVICE_SSHD_NOT_FOUND: ErrorCode = 40401

// 500xx - Internal
export const LEGACY_ERROR_SERVICE_ERROR: ErrorCode = 50001

// 999xx
export const LEGACY_ERROR_NOT_SPECIFIED: ErrorCode = 99999
