// This file is generated by generator.py
// Please do not modify this file manually

export type ErrorCode = number

export const OK: ErrorCode = 0
export const ERROR_INVALID_REQUEST: ErrorCode = 40001
export const ERROR_BUSINESS_LOGIC_ERROR: ErrorCode = 40002
export const ERROR_TOKEN_EXPIRED: ErrorCode = 40101
export const ERROR_TOKEN_INVALID: ErrorCode = 40102
export const ERROR_INVALID_CREDENTIALS: ErrorCode = 40111
export const ERROR_LDAP_ERROR: ErrorCode = 40112
export const ERROR_LDAP_USER_NOT_FOUND: ErrorCode = 40113
export const ERROR_LEGACY_TOKEN_NOT_SUPPORTED: ErrorCode = 40114
export const ERROR_MUST_REGISTER: ErrorCode = 40121
export const ERROR_UID_SERVICE_ERROR: ErrorCode = 40122
export const ERROR_UID_NOT_FOUND: ErrorCode = 40123
export const ERROR_USER_NOT_ALLOWED: ErrorCode = 40301
export const ERROR_USER_EMAIL_NOT_VERIFIED: ErrorCode = 40302
export const ERROR_SERVICE_SSHD_NOT_FOUND: ErrorCode = 40401
export const ERROR_SERVICE_ERROR: ErrorCode = 50001
export const ERROR_NOT_SPECIFIED: ErrorCode = 99999
