apiVersion: v1
kind: ConfigMap
metadata:
  name: ss-config
  namespace: {{ .Values.global.namespace | default .Values.backendConfig.workspace.namespace }}
data:
  config.yaml: |
    {{ .Values.ssConfig.content | nindent 4 | trim }}
