{{- if .Values.storage.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backendConfig.workspace.rwxpvcName}}
  namespace: {{ .Values.global.namespace | default .Values.backendConfig.workspace.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.request }}
  storageClassName: {{ .Values.storage.storageClass}}
{{- end -}}