apiVersion: v1
kind: Service
metadata:
  name: webdav-service
  namespace: {{ .Values.namespaces.job }}
  labels:
    name: webdav-service
spec:
  selector:
    app: webdav-crater
  type: ClusterIP
  ports:
    - port: 7320
      targetPort: 7320
      protocol: TCP