{{- if .Values.backendConfig.registry.enable -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: buildkit-secret
  namespace: {{ .Values.namespaces.image }}
data:
  .dockerconfigjson: {{ template "dockerconfigjson" . }}
{{- end -}}
