apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
data:
  config.yaml: |
    {{ toYaml .Values.backendConfig | nindent 4 | trim }}
