{{- if .Values.grafanaProxy.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-proxy-conf
  namespace: {{ .Release.Namespace }}
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      include /etc/nginx/mime.types;
      default_type application/octet-stream;
      server {
        listen 80;
        server_name localhost;
        location / {
          proxy_pass {{ .Values.grafanaProxy.address }};
          proxy_set_header Authorization "{{ .Values.grafanaProxy.token }}";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
{{- end }}