{{- if .Values.grafanaProxy.enable -}}
apiVersion: v1
kind: Service
metadata:
  name: grafana-proxy
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
{{- end -}}