{{- if .Values.quotaAgent.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: crater-quota-agent-auth
  namespace: {{ .Values.namespaces.job }}
  labels:
    app: crater-quota-agent
type: Opaque
data:
  internal-token: {{ printf "crater-storage-quota:%s" .Values.backendConfig.auth.token.accessTokenSecret | sha256sum | b64enc }}
{{- end }}
