{
 "title": "Better NVIDIA DCGM Dashboard",
 "description": "This dashboard displays metrics from a DCGM Exporter on a Kubernetes cluster.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU ID",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Basic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU Avgerage Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$host\", gpu=~\"$gpu\"})"
      }
     ]
    },
    {
     "title": "GPU Power Total",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$host\", gpu=~\"$gpu\"})"
      }
     ]
    },
    {
     "title": "GPU Energy Draw Total",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watth" } },
     "targets": [
      {
       "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$host\", gpu=~\"$gpu\"}[1h]) / 3600000)",
       "legendFormat": "Last 1h"
      },
      {
       "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$host\", gpu=~\"$gpu\"}[24h]) / 3600000)",
       "legendFormat": "Last 24h"
      }
     ]
    },
    {
     "title": "GPU Power Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$host\", gpu=~\"$gpu\"}",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"}",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Memory Used Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"} / (DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"} + DCGM_FI_DEV_FB_FREE{Hostname=~\"$host\", gpu=~\"$gpu\"})",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$host\", gpu=~\"$gpu\"}",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU SM Clocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 161 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$host\", gpu=~\"$gpu\"} * 1000000",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$host\", gpu=~\"$gpu\"}",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    },
    {
     "title": "Tensor Core Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$host\", gpu=~\"$gpu\"}",
       "legendFormat": "{{Hostname}} - GPU {{gpu}}"
      }
     ]
    }
   ]
  },
  { "title": "Prof", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "DCGM_FI_PROF_DRAM_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_DRAM_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP16_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP16_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_SM_OCCUPANCY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_OCCUPANCY\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_SM_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_SM_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP64_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP64_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "DCGM_FI_PROF_PIPE_FP32_ACTIVE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "DCGM_FI_PROF_PIPE_FP32_ACTIVE\n{Hostname=~\"$host\", gpu=~\"$gpu\"}",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  }
 ]
}