{
 "title": "Crater Node NVIDIA Dashboard",
 "description": "This dashboard displays metrics from a DCGM Exporter on a Kubernetes cluster.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU ID",
    "query": "label_values(DCGM_FI_DEV_GPU_TEMP, gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "GPU 平均温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$host\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU 总功耗",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$host\", gpu=~\"$gpu\"})"
    }
   ]
  },
  {
   "title": "GPU 总能耗",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$host\", gpu=~\"$gpu\"}[1h]) / 3600000)",
     "legendFormat": "Last 1h"
    },
    {
     "expr": "sum(increase(DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION{Hostname=~\"$host\", gpu=~\"$gpu\"}[24h]) / 3600000)",
     "legendFormat": "Last 24h"
    }
   ]
  },
  {
   "title": "GPU 平均利用率 ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "运行中作业",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$host\", namespace=\"crater-workspace\",gpu=~\"$gpu\"} * on (pod) group_left(host_ip) kube_pod_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "(DCGM_FI_DEV_FB_USED{Hostname=~\"$host\",namespace=\"crater-workspace\",gpu=~\"$gpu\"}/(DCGM_FI_DEV_FB_USED{Hostname=~\"$host\",namespace=\"crater-workspace\",gpu=~\"$gpu\"}+DCGM_FI_DEV_FB_FREE{Hostname=~\"$host\",namespace=\"crater-workspace\",gpu=~\"$gpu\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Tensor Core 平均利用率 ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG(DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU 利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "Tensor Core 利用率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_PROF_PIPE_TENSOR_ACTIVE{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 显存使用占比",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"} / (DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"} + DCGM_FI_DEV_FB_FREE{Hostname=~\"$host\", gpu=~\"$gpu\"}))",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 显存用量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_FB_USED{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Copy 利用率",
   "type": "timeseries",
   "description": "GPU 设备在内存复制操作过程中的利用率",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU 温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$host\", gpu=~\"$gpu\"})",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by (Hostname,gpu) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$host\", gpu=~\"$gpu\"} * 1000000)",
     "legendFormat": "{{Hostname}} - GPU {{gpu}}"
    }
   ]
  }
 ]
}